Feature/file system
rapidcore/rapidcore pull request #1
Opened 2017-05-18 09:47 UTC by MartinsRui

2017-05-18 11:31 UTC, nover requested changes

2017-05-18 11:31 UTC, nover commented on src/IO/FileSystem/DotNetFileSystemProvider.cs
> +        Stream IFileSystemProvider.OpenReadFile(string path)
Is there need for an explicit interface reference here?

2017-05-18 11:31 UTC, nover commented on src/IO/FileSystem/DotNetFileSystemProvider.cs
> +        public void Move(string sourceFile, string destFile)
No documentation for Move function

2017-05-18 11:31 UTC, nover commented on src/rapidcore.csproj
> +  <ItemGroup>
Is this reference required when we move to netstandard 1.6?

2017-05-18 12:10 UTC, MartinsRui commented on src/rapidcore.csproj
> +  <ItemGroup>
not required anymore.
fixed.

2017-05-18 12:10 UTC, MartinsRui commented on src/IO/FileSystem/DotNetFileSystemProvider.cs
> +        public void Move(string sourceFile, string destFile)
fixed

2017-05-18 12:10 UTC, MartinsRui commented on src/IO/FileSystem/DotNetFileSystemProvider.cs
> +        Stream IFileSystemProvider.OpenReadFile(string path)
fixed

2017-05-19 06:49 UTC, nover approved these changes

2017-05-19 06:50 UTC, merged