WIP Feature/write all lines i file system provider
rapidcore/rapidcore pull request #7
Opened 2017-05-26 14:34 UTC by MartinsRui

Currently can not write tests for SftpFileSystemProvider since there is no interface for it.
Waiting on a pull request to be accepted on SSH.NET's github

2017-08-09 14:41 UTC, MartinsRui commented
created the interface for ISftpClient locally

2017-08-10 05:35 UTC, pingvinen requested changes

2017-08-10 05:35 UTC, pingvinen commented on test/unit/IO/FileSystem/SftpFileSystemProviderTest.cs
> +        public void Can_ListDirectoryWithSearchPattern()
The test does not prove that it returns only elements that match the given search pattern.

2017-08-10 05:35 UTC, pingvinen commented on test/unit/IO/FileSystem/SftpFileSystemProviderTest.cs
> +        public void Can_OpenReadAFile()
The test does not check the return value.

2017-08-10 05:35 UTC, pingvinen commented on test/unit/IO/FileSystem/SftpFileSystemProviderTest.cs
> +        public void Can_ListDirectory()
The test does not check the return value.

2017-08-10 05:35 UTC, pingvinen commented on test/unit/IO/FileSystem/SftpFileSystemProviderTest.cs
> +        public void Can_LoadContentOfAFile()
The test does not check the return value.

2017-08-10 05:35 UTC, pingvinen commented on test/unit/IO/FileSystem/SftpFileSystemProviderTest.cs
> +        public void Can_CreateDirectory()
The test does not check the return value.

2017-08-10 08:39 UTC, MartinsRui commented
@pingvinen one more time :)

2017-08-10 08:50 UTC, pingvinen submitted a review, later dismissed

2017-08-10 08:52 UTC, pingvinen approved these changes

2017-08-10 09:07 UTC, merged